version: '3.8'

services:
  backend:
    restart: always
    build:
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    networks:
      - chpk
    ports:
      - "3000:3000"

  front:
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3000/
    networks:
      - chpk
    ports:
      - '3002:3002'

networks:
  chpk:
    driver: bridge